-- Book insights generated by Claude API
CREATE TABLE book_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  why_read TEXT NOT NULL,
  themes TEXT[] NOT NULL DEFAULT '{}',
  quotes TEXT[] NOT NULL DEFAULT '{}',
  related_book_ids UUID[] DEFAULT '{}',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_id UUID NOT NULL
);

CREATE UNIQUE INDEX idx_book_insights_book_id ON book_insights(book_id);
