-- 006_suggested_books.sql
-- Adds suggested_books JSONB column to book_insights for storing
-- external book recommendations generated by Claude.
-- Each entry: { title, authors, cover_image_url, isbn_13, reasoning }

ALTER TABLE book_insights
ADD COLUMN suggested_books jsonb DEFAULT '[]';
